### ISSUE TITLE
Code for EDB module and Depth Edges Loss

### ISSUE THREAD

**Issue by Shaw-Way** [liortalker/MindTheEdge#2]
Hello, thanks for your remarkable work. Can you share the Code for EDB module and Depth Edges Loss. Thanks in advance!

**Comment by liortalker** [comment]
Hi, thanks for your interest!
We plan to release the code in a few weeks (including the EDB and Depth Edges Loss).
Will keep you updated.

**Comment by liortalker** [comment]
Sorry for the delay, we are currently working to understand under which license we can release the code.
Will keep you posted.

**Comment by liortalker** [comment]
Hi,
Finally added the code and weights for inference and training.
The depth edges loss and EDB are here: packnet_code/packnet_sfm/losses/grad_loss.py
